### ISSUE TITLE
Error in global-proxy-mode

### ISSUE THREAD

**Issue by seagle0128** [stardiviner/proxy-mode#1]
I like `proxy-mode`, but while enabling `global-proxy-mode`, I got this error.

GNU Emacs 26.1
macOS 10.13

```elisp
Error in minibuffer-exit-hook (pl/minibuffer-exit): (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
ivy-read: Lisp nesting exceeds ‘max-lisp-eval-depth’
Error in post-command-hook (global-proxy-mode-check-buffers): (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
```

**Comment by stardiviner** [comment]
Yes, I can confirmed on this `global-proxy-mode`. temporary I can't solve it. I take this implementation from someone's advice. I will find a way to fix it when I have time on this. But I rencently, I'm busy on other things. Anyway, PR welcome, anyone.

**Comment by stardiviner** [comment]
Should be fixed in latest commit.

**Comment by seagle0128** [comment]
This issue has been fixed. But I can confirm, `proxy-mode` doesn't work :(

**Comment by seagle0128** [comment]
`proxy-mode` doesn't list the options (HTTP/SOCKS/URL) now. `global-proxy-mode` is enabled, but the proxy doesn't work.

BTW, should add `###autoload` to `(define-globalized-minor-mode global-proxy-mode proxy-mode proxy-mode)` .

The config:
```elisp
(use-package proxy-mode
  :init
  (define-globalized-minor-mode global-proxy-mode proxy-mode proxy-mode)
  (setq proxy-mode-http-proxy "http://127.0.0.1:1087")
  (setq proxy-mode-socks-proxy '("Default server" "127.0.0.1" 1086 5))

  (setq proxy-mode-url-proxy '(("http"  . "127.0.0.1:1087")
                               ("https" . "127.0.0.1:1087")
                               ("ftp"   . "127.0.0.1:1087")
                               ;; don't use `localhost', avoid robe server (For Ruby) can't response.
                               ("no_proxy" . "127.0.0.1")
                               ("no_proxy" . "^.*\\(baidu\\|sina)\\.com")))

  (setq url-gateway-local-host-regexp
        (concat "\\`" (regexp-opt '("localhost" "127.0.0.1")) "\\'")))
```

**Comment by stardiviner** [comment]
Hum, just a few minutes ago, I suddenly remember I change `proxy-mode-enable` into `(interactive ..)`, it need to be called with `call-interactive` now. I tested, the proxy-mode toggle can select proxy now. But then the max-lisp-depth error popup again. WTF?!

**Comment by stardiviner** [comment]
I decide to disable `global-proxy-mode` temporary. Because usually user will not use it in all buffers. Until I know how to figure it out, I will enable it again. @seagle0128  what do you think?

**Comment by seagle0128** [comment]
Actually I'd like suggest to use `setq` instead of `setq-local`, so that the proxy should be working in all buffers.

**Comment by stardiviner** [comment]
I can't understand `define-globalized-minor-mode`, isn't should apply `proxy-mode` on all buffers? If so, might need to use `setq` instead of `setq-local` in `global-proxy-mode` separately. But still don't understand why `global-proxy-mode` should apply `proxy-mode` on all buffers caused error.

**Comment by seagle0128** [comment]
The root cause is `interactive` in `proxy-mode-enable`, I guess?

**Comment by stardiviner** [comment]
Yes, I tried remove it, then like you said, the proxy selection is not available them.

**Comment by seagle0128** [comment]
Well, I will try to help on that when I have some time.

**Comment by stardiviner** [comment]
Thanks!

**Comment by stardiviner** [comment]
@seagle0128 发现这个issue还没解决，研究了一下也没找到办法，知道你是emacs-china的大神，所以问问你能解决不？

**Comment by stardiviner** [comment]
Can I see them? I'd like to check them out maybe can inspire me. Thanks in advance.

**Comment by seagle0128** [comment]
很简单的函数，可能帮不上你什么

https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-funcs.el#L171
